language: rust
env:
  global:
    - secure: HRSy8ISmoYsdp2Sf4J0KXOs6a3xHU1dF4orSoOhewDM2wFRgO45VVzPnfEm0I3qMi72UQi+FmM1APHnbBrMhXLU2sMn/qE5Zy8uW5hmDTkFVBiUcOqYnrHLv8mKTl20ze/Rd8+DHEF0IYaObSX9317O8DZChepoHkOiHkR3rlB0=
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libmagic1 libmagic-dev
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose
after_script:
  # the doc directory needs to be in the root for rust-ci
  - mv target/doc doc
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
