[package]

name = "magic-sys"
description = "Declarations for `libmagic`"
homepage = "https://github.com/robo9k/rust-magic-sys"
documentation = "http://rust-ci.org/robo9k/rust-magic-sys/doc/magic-sys/"
repository = "https://github.com/robo9k/rust-magic-sys.git"
license = "MIT"
version = "0.0.5"
authors = ["robo9k <robo@9k.lv>"]
links = "magic"
build = "build.rs"
