[package]

name = "magic-sys"
description = "Declarations for `libmagic`"
readme = "README.md"
keywords = [
    "magic",
    "file",
]
repository = "https://github.com/robo9k/rust-magic-sys.git"
license = "MIT/Apache-2.0"
version = "0.2.1"
authors = ["robo9k <robo@9k.lv>"]
links = "magic"
build = "build.rs"
exclude = [
    ".gitignore",
    ".gitattributes",
    "/.github/",
    "/.vscode/",
    "rust-toolchain.toml",
    "shell.nix",
    "nix/",
]
rust-version = "1.38"

[features]
default = ["libmagic-abi-v540"]
libmagic-abi-v504 = []
libmagic-abi-v505 = ["libmagic-abi-v504"]
libmagic-abi-v510 = ["libmagic-abi-v505"]
libmagic-abi-v513 = ["libmagic-abi-v510"]
libmagic-abi-v520 = ["libmagic-abi-v513"]
libmagic-abi-v521 = ["libmagic-abi-v520"]
libmagic-abi-v522 = ["libmagic-abi-v521"]
libmagic-abi-v523 = ["libmagic-abi-v522"]
libmagic-abi-v525 = ["libmagic-abi-v523"]
libmagic-abi-v527 = ["libmagic-abi-v525"]
libmagic-abi-v532 = ["libmagic-abi-v527"]
libmagic-abi-v535 = ["libmagic-abi-v532"]
libmagic-abi-v538 = ["libmagic-abi-v535"]
libmagic-abi-v540 = ["libmagic-abi-v538"]

[dependencies]
libc = "0.2.13"

[build-dependencies]
vcpkg = "0.2.15"

[package.metadata.vcpkg]
git = "https://github.com/microsoft/vcpkg"
rev = "078f3e5"
dependencies = ["libmagic"]

[package.metadata.vcpkg.target]
x86_64-pc-windows-msvc = { triplet="x64-windows-static-md" }

[package.metadata]
msrv = "1.38.0"
