[package]

name = "magic-sys"
description = "Declarations for `libmagic`"
readme = "README.md"
keywords = [
    "magic",
    "file",
]
repository = "https://github.com/robo9k/rust-magic-sys.git"
license = "MIT/Apache-2.0"
version = "0.2.1"
authors = ["robo9k <robo@9k.lv>"]
links = "magic"
build = "build.rs"
exclude = [
    ".gitignore",
    ".travis.yml",
]

[dependencies]
libc = "0.2.13"
