[package]

name = "magic-sys"
description = "Declarations for `libmagic`"
readme = "README.md"
keywords = [
    "magic",
    "file",
]
repository = "https://github.com/robo9k/rust-magic-sys.git"
license = "MIT/Apache-2.0"
version = "0.2.1"
authors = ["robo9k <robo@9k.lv>"]
links = "magic"
build = "build.rs"
exclude = [
    ".gitignore",
    "/.github/",
]

[dependencies]
libc = "0.2.13"

[build-dependencies]
vcpkg = "0.2.15"

[package.metadata.vcpkg]
git = "https://github.com/microsoft/vcpkg"
rev = "078f3e5"
dependencies = ["libmagic"]

[package.metadata.vcpkg.target]
x86_64-pc-windows-msvc = { triplet="x64-windows-static-md" }
