[package]

name = "magic-sys"
description = "Declarations for `libmagic`"
readme = "README.md"
keywords = [
    "magic",
    "file",
]
homepage = "https://github.com/robo9k/rust-magic-sys"
documentation = "https://robo9k.github.io/rust-magic-sys/magic-sys/"
repository = "https://github.com/robo9k/rust-magic-sys.git"
license = "MIT"
version = "0.0.8"
authors = ["robo9k <robo@9k.lv>"]
links = "magic"
build = "build.rs"
exclude = [
    ".gitignore",
    ".travis.yml",
]

[dependencies]
libc = "0.1.8"
